### ISSUE TITLE
I got a error using imagemanager, i need help please

### ISSUE THREAD

**Issue by vapinedo** [noam148/yii2-image-manager#27]
#Hi someone can i help me?, i have installed the imagemanager extension on yii2, but when  i try to upload a image something fails.

am using de advanced template yii2, and i'm working on local on MAC.

here is a 3  snapshots about the issue:

**1) The view _form where i use de widget imagemanager:**
![image](https://cloud.githubusercontent.com/assets/9469225/26036379/2ff2dc88-38a2-11e7-930e-234d4f34a81e.png)

**2) The error I get trying to upload the image:**
![image](https://cloud.githubusercontent.com/assets/9469225/26036401/86d0bb4c-38a2-11e7-99be-f8e0581045d5.png)

**3)The error I get when trying to select any image:**
![image](https://cloud.githubusercontent.com/assets/9469225/26036403/a11d8e58-38a2-11e7-9ae0-8a621480d179.png)

Many thanks beforehand whoever can help me!!!

**Comment by bvanleeuwen1995** [comment]
Could you please give a screenshot of any request that fails and the response it gives? This error message means that somewhere a error was found, but in order to drive into this we need the error message.

I have just tested it on my local installation with your settings, and had no error sadly so I could not pinpoint it for you.

**Comment by noam148** [comment]
Please update to the last release. I update the code and this give you a new error with more details. And send me the error.

- I have some questions. Is the image uploaded when you get that error or is the image not uploaded? I ask that because i see other images (already uploaded). 
- What diffrence between the image that's already been uploaded and the image that can't upload?

Let me know so I can help you!

**Comment by vapinedo** [comment]
**Good answering the question of _noam148_, ie the following questions:**

**1) ¿Is the image uploaded when you get that error or is the image not uploaded? I ask that because i see other images (already uploaded). ?**

**The Answer**
The truth is when I try to upload an image, actually to the image if it is uploaded to the server correctly, but ... what happens is that the image is loading and I have to close and reopen the imagenanager window in order to see the image just uploaded.

**2) ¿What difference between the image that's already been uploaded and the image that can't upload?** 

**the Answer**
The problem is that once I upload an image, when trying to select it by clicking on it, it throws me an error message that says: can not get the data (ie the data of the image.)

**Note**
Well the truth the extension installed just yesterday May 13, 2017, is there a new and recent version of it?

Thanks for everything and sorry for writing so much in my reply.

**Comment by noam148** [comment]
Thanks for answering my questions! Yes I create yesterday (May 14, 2017) a update. And this small release change the error message and give it some more details. 

So when you update it and you try to upload a image again you will get an error with more info. 

Let me know what the message is ;)

**Comment by noam148** [comment]
Re-open it, if you have any questions or need more help.
