### ISSUE TITLE
error: table not exist

### ISSUE THREAD

**Issue by igorveremsky** [noam148/yii2-image-manager#47]
after install extension get error
![screenshot_264](https://user-images.githubusercontent.com/13087365/40553526-9ca8bf88-604b-11e8-9d60-2253d347ab13.png)

**Comment by bvanleeuwen1995** [comment]
Did you run the included migrations before trying to use the image manager?

**Comment by igorveremsky** [comment]
@bvanleeuwen1995 yes, of course :) why will i changed migration at https://github.com/igorveremsky/yii2-image-manager/commit/4c963d8f479ed3f05dd48a50780aa275071f5dd1 if i don`t run it

**Comment by Nagibaba** [comment]
in Yii2 image manager the table name is defined as `ImageManager`, but in my case table name on DB is `imagemanager`. Change table name to the same case from DB

**Comment by igorveremsky** [comment]
@Nagibaba what do you mean as `Yii2 image manager`? issue already closed because by change  table name to `imagemanager` at extension migrations

**Comment by igorveremsky** [comment]
@Nagibaba at 1.2.10 release - https://github.com/noam148/yii2-image-manager/releases/tag/1.2.10

**Comment by bvanleeuwen1995** [comment]
@Nagibaba is correct, the code changes broke any existing installations, mind you it isn't a problem for example in Postgres, since Postgres converters to lower case anyway, but I have various applications applications that use MySQL that now require manual patching

@noam148 can you please reopen this ticket since the PR made changes to the module for already existing applications, this will need fixing ASAP

**Comment by noam148** [comment]
@Nagibaba @bvanleeuwen1995 there is a new release. It is fixed in 1.2.11. Can you check?
