### ISSUE TITLE
use it in the editor like wysiwyg or tinymice

### ISSUE THREAD

**Issue by vc7deo** [noam148/yii2-image-manager#6]
can we use it in image button of the editors like wysiwyg or the tinymice

**Comment by noam148** [comment]
That's a good idea, if i got some time this week I will check the possibilities.

**Comment by vc7deo** [comment]
Thank you..I have one more doubt.

![image](https://cloud.githubusercontent.com/assets/8149102/19721271/29ee3202-9b8f-11e6-8778-dd28964640b1.png)

instead of using file name like this can we use the actual filename stored in the database.so this is very helpful for the seo if we use the images in frontend

**Comment by noam148** [comment]
For the second issue I need to create a own image thumbnail helper. At the moment I use the thumbnail helper "himiklab/yii2-easy-thumbnail-image-helper" and so far I know thats not possible with this helper component.

This weekend I hope to work on it, I let you know if there is an update!

**Comment by noam148** [comment]
@vc7deo with the last commit its now possible to use the imagemanager in CKEditor and TinyMCE. See README for instructions. Don't forget the clear the assets after update.

I create a new issue for the issue with the filename. For that i need to build a new component so that for later. I let you know when that done.

**Comment by vc7deo** [comment]
@noam148 great work... its working perfectly
